<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{{ asset('css/bootstrap.min.css') }}">
</head>
<body>
<div class="container mt-5">
    <h1>Password Reset Successful!</h1>

    <div class="row">
        <div class="col-md-12 text-center">
            <p>Your password has been successfully updated. Your new password has been generated by the system and is as follows:</p>

            <p>{{ $newPassword }}</p>

            <p>Please keep this password safe and do not share it with anyone. We recommend that you change your password periodically to ensure the security of your account.</p>
        </div>
    </div>
</div>


<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="{{ asset('js/bootstrap.min.js') }}"></script>
</body>
</html>
